# Generated by Django 5.0.7 on 2024-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (10, 'DOING'), (20, 'DONE')], default=0)),
                ('priority', models.IntegerField(choices=[(0, 'LOW'), (10, 'MEDIUM'), (20, 'HIGH'), (30, 'URGENT')], default=0)),
            ],
        ),
    ]
