# Generated by Django 5.0.7 on 2024-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
